module.exports = {
  "ALIVE_IMG": "No image ",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "inbox",
  "BOT_NUMBER": "923361937779",
  "OMDB_API_KEY": "1KMH6VGB",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": true,
  "WELCOME": true,
  "ANTI_BAD": false,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ANTI_CALL": false,
  "ANTI_DELETE": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "M Shahid",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": true,
  "EMOJI": "❤️🤖💔Aq"
};
